import type { UnitMap } from '../types'

export const UNITS: UnitMap = {
  1: {
    title: 'NLP Overview',
    icon: '◈',
    accent: '#00D4FF',
    glow: 'rgba(0,212,255,0.10)',
    topics: [
      'History and Applications of NLP',
      'Information Retrieval (IR) in NLP',
      'Information Extraction techniques',
      'Question Answering Systems',
      'Sentiment Analysis',
      'Optical Character Recognition (OCR)',
      'Text Summarization techniques',
      'Spell and Grammar Checking',
      'Text Categorization and Word Prediction',
      'Speech Recognition',
      'Machine Translation',
      'Types of Ambiguity in NLP (Lexical, Syntactic, Semantic, Pragmatic)',
      'NLP Terminology and Components',
    ],
  },
  2: {
    title: 'NLP Techniques',
    icon: '◇',
    accent: '#FF6B6B',
    glow: 'rgba(255,107,107,0.10)',
    topics: [
      'Parts of Speech (POS) Tagging overview',
      'Rule-based POS Tagging',
      'Hidden Markov Model (HMM) POS Tagging',
      'Viterbi Algorithm for HMM Tagging',
      'Phonology in NLP',
      'Probabilistic Speech Recognition',
      'Morphology and Morphological Parsing',
      'Finite State Morphological Parsing',
      'Tokenization in NLP',
      'Stemming and Lemmatization',
      'Regular Expressions for NLP',
      'Finite State Automata (Deterministic and Non-Deterministic)',
    ],
  },
  3: {
    title: 'Probabilistic Language Models',
    icon: '○',
    accent: '#FFD93D',
    glow: 'rgba(255,217,61,0.10)',
    topics: [
      'Porter Stemmer Algorithm',
      'Spelling Error Detection and Correction',
      'Minimum Edit Distance algorithm',
      'Bag of Words model with N-Gram',
      'Chain Rule in Language Modeling',
      'N-Gram Language Models',
      'Unigram and Bigram Models',
      'Evaluating N-Grams with Perplexity',
      'Laplace Smoothing in NLP',
      'Interpolation in Language Models',
      'Context Free Grammar (CFG)',
      'Top Down Parsing',
    ],
  },
  4: {
    title: 'Neural Networks in NLP',
    icon: '△',
    accent: '#6BCB77',
    glow: 'rgba(107,203,119,0.10)',
    topics: [
      'Introduction to Neural Networks for NLP',
      'Neural Network Architecture for NLP',
      'Recurrent Neural Networks (RNN) in NLP',
      'Word Sense Disambiguation',
      'WordNet lexical database',
      'Learning Representations in NLP',
      'Backpropagation in Neural Networks',
      'Vectorization for NLP',
      'Dependency Parsing in NLP',
      'Fast Neural Network Dependency Parser',
      'Globally Normalized Transition-Based Neural Networks',
    ],
  },
  5: {
    title: 'NLP and Deep Learning',
    icon: '✦',
    accent: '#C77DFF',
    glow: 'rgba(199,125,255,0.10)',
    topics: [
      'Introduction to Deep Learning for NLP',
      'Word Vectors and Word2Vec',
      'Distributed Representations of Words',
      'GloVe Vectors for Word Representation',
      'Word Representations in Vector Space',
      'Improving Distributional Similarity',
      'Evaluation Methods for Unsupervised Word Embeddings',
      'Pretrained Language Models (BERT, GPT)',
      'Transfer Learning in NLP',
      'Long Short-Term Memory (LSTM)',
    ],
  },
} as const

export const UNIT_NUMBERS = [1, 2, 3, 4, 5] as const
export type UnitNumber = (typeof UNIT_NUMBERS)[number]
